### ISSUE TITLE
[feat] Add an optional configuration, enter the directory directly after cloning

### ISSUE THREAD

**Issue by TinsFox** [xn-sakina/tanyao#4]
Sometimes it needs a lazy person to operate. After cloning, it is usually necessary to cd into it. Add an optional option in config.json or add command line parameters to achieve it?

If possible, this can be achieved by me.

**Comment by fz6m** [comment]
PR Welcome

**Comment by TinsFox** [comment]
There is no way to modify the current working path of terminal in node
